export const items = [
  { name: "rice", emoji: "🍚", label: "Arroz" },
  { name: "tomato", emoji: "🍅", label: "Tomate" },
  { name: "chicken", emoji: "🍗", label: "Frango" },
  { name: "beef", emoji: "🥩", label: "Carne de boi" },
  { name: "onion", emoji: "🧅", label: "Cebola" },
  { name: "carrot", emoji: "🥕", label: "Cenoura" },
  { name: "potato", emoji: "🥔", label: "Batata" },
  { name: "egg", emoji: "🥚", label: "Ovo" },
  { name: "lettuce", emoji: "🥬", label: "Alface" },
  { name: "corn", emoji: "🌽", label: "Milho" },
  { name: "shrimp", emoji: "🍤", label: "Camarão" },
  { name: "honey", emoji: "🍯", label: "Mel" },
  { name: "milk", emoji: "🥛", label: "Leite" },
  { name: "butter", emoji: "🧈", label: "Manteiga" },
  { name: "garlic", emoji: "🧄", label: "Alho" },
  { name: "bacon", emoji: "🥓", label: "Bacon" },
  { name: "sweet-potato", emoji: "🍠", label: "Batata-doce" },
  { name: "cheese", emoji: "🧀", label: "Queijo" },
  { name: "bread", emoji: "🍞", label: "Pão" },
  { name: "pinto-beans", emoji: "🫘", label: "Feijão" },
  { name: "fish", emoji: "🐟", label: "Peixe" },
  { name: "broccoli", emoji: "🥦", label: "Brócolis" },
  { name: "strawberry", emoji: "🍓", label: "Morango" },
  { name: "banana", emoji: "🍌", label: "Banana" },
  { name: "lemon", emoji: "🍋", label: "Limão" },
  { name: "orange", emoji: "🍊", label: "Laranja" },
  { name: "grapes", emoji: "🍇", label: "Uva" },
  { name: "melon", emoji: "🍈", label: "Melão" },
  { name: "watermelon", emoji: "🍉", label: "Melancia" },
  { name: "avocado", emoji: "🥑", label: "Abacate" },

  // //
  // { name: "eggplant", emoji: "🍆", label: "Beringela" },
  // { name: "cucumber", emoji: "🥒", label: "Pepino" },
  // { name: "chili-pepper", emoji: "🌶️", label: "Pimenta" },
  // { name: "bell-pepper", emoji: "🫑", label: "Pimentão" },
  // //
  // { name: "mushroom", emoji: "🍄", label: "Cogumelo" },
  // { name: "chestnut", emoji: "🌰", label: "Castanha" },
  // { name: "coconut", emoji: "🥥", label: "Coco" },
  // { name: "peanut", emoji: "🥜", label: "Amendoim" },
  // //
  // { name: "mango", emoji: "🥭", label: "Manga" },
  // { name: "pineapple", emoji: "🍍", label: "Abacaxi" },
  // { name: "apple", emoji: "🍎", label: "Maçã" },
  // { name: "pear", emoji: "🍐", label: "Pêra" },
  // { name: "peach", emoji: "🍑", label: "Pêssego" },
  // { name: "kiwi-fruit", emoji: "🥝", label: "Kiwi" },
  // { name: "grapes", emoji: "🍇", label: "Uva" },
  // { name: "banana", emoji: "🍌", label: "Banana" },
  // { name: "strawberry", emoji: "🍓", label: "Morango" },
  // { name: "blueberries", emoji: "🫐", label: "Mirtilo" },
  // { name: "lemon", emoji: "🍋", label: "Limão" },
  // { name: "orange", emoji: "🍊", label: "Laranja" },
  // { name: "watermelon", emoji: "🍉", label: "Melancia" },
  // { name: "cherries", emoji: "🍒", label: "Cereja" },
  // { name: "avocado", emoji: "🥑", label: "Abacate" },
  // { name: "baguette-bread", emoji: "🥖", label: "Baguete" },
  // { name: "croissant", emoji: "🥐", label: "Croissant" },
];
